### ISSUE TITLE
Release git history borked

### ISSUE THREAD

**Issue by PaulHax** [Kitware/nrtk-explorer#128]
Looks like we forgot to merge 0.3.2 release back into main.  When I erroniously rebaseed main to release for the 0.4.0 release, the merge from release to main will add duplicate commits. 

- [x] fix git history
- [x] Document click by click release steps here: https://github.com/Kitware/nrtk-explorer/pull/127/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R69-R73
- [ ] Maybe simplify steps.  Like just target main for manual semantic release job and drop release branch.

**Comment by vicentebolea** [comment]
There is a CI job that merges release to main after every commit in release. Unfortunately it did not trigger since there has been a change in the branches settings for push requirements. 

The error was:   `Changes must be made through a pull request. // See: https://docs.github.com/rest/branches/branches#merge-a-branch` I have changed the settings to solve this.

The rationale for having a release branch is that we wanted to have an state in master that was different to the release. This was specially important for features that took multiple PRs. Having a release branch gives us control into what goes in a release (which it was needed).

**Comment by vicentebolea** [comment]
There are not duplicated commits, there are either backported commits to the release branch (that was the reason of having a release branch) or you are seeing a merge commit. We want to always merge release to main (we do an -s ours merge) to avoid future merge conflicts.

**Comment by PaulHax** [comment]
Is it OK that we don't automaticly merge release back to main after semantic release makes its version commit?

Do we need to merge release back to main for 0.4.0 right now?

**Comment by vicentebolea** [comment]
> Is it OK that we don't automaticly merge release back to main after semantic release makes its version commit?

It is safer to merge after releases so that releases are reachable from main and also we avoid potential merge conflicts in the future.

> Do we need to merge release back to main for 0.4.0 right now?

it is already merged https://github.com/Kitware/nrtk-explorer/commit/1c9359e87b4e0255ab232b32263680f8314f043f

**Comment by vicentebolea** [comment]
You might want to close this since this was solved by restoring the github branch settings.
